// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDw7_mBa4BA0lQs2c2K69ZFht_RCZ9XsQ',
    appId: '1:897707411351:web:155a1a040638b206b3a6d2',
    messagingSenderId: '897707411351',
    projectId: 'dapurku-64c1f',
    authDomain: 'dapurku-64c1f.firebaseapp.com',
    storageBucket: 'dapurku-64c1f.firebasestorage.app',
    measurementId: 'G-HLDY6MXWXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8iGhRIz7l5Mawy4OC2NNq1upZoeCqCEM',
    appId: '1:897707411351:android:769c79206d19c1ceb3a6d2',
    messagingSenderId: '897707411351',
    projectId: 'dapurku-64c1f',
    storageBucket: 'dapurku-64c1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3qJSHr17yuPPpZIWkmSmEmFKZrNIum5w',
    appId: '1:897707411351:ios:7b6e56358c1cd2c3b3a6d2',
    messagingSenderId: '897707411351',
    projectId: 'dapurku-64c1f',
    storageBucket: 'dapurku-64c1f.firebasestorage.app',
    iosBundleId: 'com.example.dapurku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3qJSHr17yuPPpZIWkmSmEmFKZrNIum5w',
    appId: '1:897707411351:ios:7b6e56358c1cd2c3b3a6d2',
    messagingSenderId: '897707411351',
    projectId: 'dapurku-64c1f',
    storageBucket: 'dapurku-64c1f.firebasestorage.app',
    iosBundleId: 'com.example.dapurku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDw7_mBa4BA0lQs2c2K69ZFht_RCZ9XsQ',
    appId: '1:897707411351:web:32bc461e646275f6b3a6d2',
    messagingSenderId: '897707411351',
    projectId: 'dapurku-64c1f',
    authDomain: 'dapurku-64c1f.firebaseapp.com',
    storageBucket: 'dapurku-64c1f.firebasestorage.app',
    measurementId: 'G-X4J4V22D6Y',
  );
}
